#!/bin/bash
echo "Creating and populating /etc/rts2"
mkdir /etc/rts2
cp --no-clobber -v conf/rts2.ini conf/services conf/devices conf/centrald /etc/rts2
echo "Copying startup script"
if [ -d /etc/systemd ]; then
	rm /etc/init.d/rts2
	cp -v conf/rts2.service conf/rts2@.service /etc/systemd/system/
	systemctl daemon-reload
else
	cp --no-clobber -v rts2.initd /etc/init.d/rts2
fi
chmod -v a+x /etc/init.d/rts2
echo "Copying flats and guiding scripts"
cp --no-clobber -v scripts/guide.py scripts/flat.py /etc/rts2
