#!/bin/bash
echo "Creating and populating /etc/rts2"
mkdir /etc/rts2
cp -v conf/rts2.ini conf/services conf/devices conf/centrald /etc/rts2
echo "Copying startup script"
cp -v rts2.initd /etc/init.d/rts2
echo "Copying flats and guiding scripts"
cp -v scripts/rts2comm.py scripts/guide.py scripts/flats.py /etc/rts2
