#!/usr/bin/python
#   Queue targets to selector
#   version for rts2af
#   (C) 2011 Petr Kubanek, Institute of Physics <kubanek@fzu.cz>
#   (c) 2012 Markus Wildi, wildi.markus@blluewin.ch
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   Please visit http://www.gnu.org/licenses/gpl.html for license informations.

import rts2.json
from optparse import OptionParser
import sys
import string
import logging
import re

class Rts2Queue:
	def __init__(self,queue,j,service='SEL'):
		""" Initialize Queue help class. Parameter j is Rts2JSON object"""
		self.queue = queue
		self.j = j
		self.service = service

	def get_target(self,name):
		try:
			return self.j.loadJson('/api/tbyid',{'id':int(name)})['d']
		except ValueError:
			return self.j.loadJson('/api/tbyname',{'n':name})['d']
			
	def queue_target(self,ids):
		return self.j.loadJson('/api/cmd',{'d':self.service,'c':"queue {0} {1}".format(self.queue, string.join(map(str,ids),' '))})

	def clear(self):
		return self.j.loadJson('/api/cmd',{'d':self.service,'c':'clear {0}'.format(self.queue)})

	def __str__(self):
		resp = self.j.loadJson('/api/get',{'d':self.service})
		ret = ''
		for i in resp['d'][self.queue + '_ids']:
			if len(ret):
				ret += ' '
			ret += str(i)
		return ret

	def getStateEXEC(self):
                rep= self.j.loadJson('/api/get', {'d': 'EXEC', 'e' : 1})
                return rep['d']['current']
        def getStateFocuser(self, focuser):
                rep= self.j.loadJson('/api/get', {'d': focuser, 'e' : 1})
                return rep['d']['TCMODE']

        def getFocuserName(self):
# ToDo there might be a simpler solution
                rep= self.j.loadJson('/api/devbytype', {'t':3})
                camera= rep[0]
                rep= self.j.loadJson('/api/get', {'d': camera})

                return rep['d']['focuser']




if __name__ == '__main__':
        aftarget= '5'
  	parser = OptionParser()

	parser.add_option("--unique", help="only accept unique target", action='store_true', dest='unique')
	parser.add_option("--clear", help="clear given queue", action='store_true',dest='clear')
	parser.add_option("--queue", help='provide queue name', action='store', dest='queue', default='plan')
	parser.add_option('--server',help='URL to RTS2 XML-RPC server',action='store',dest='server',default='http://localhost:8889')
	parser.add_option("--user",help="user name",action="store",dest='username',default=None)
	parser.add_option("--password",help="user password",action="store",dest='password',default=None)
	parser.add_option('--verbose',help='print in/out communication',action='store_true',dest='verbose',default=False)
	parser.add_option("--aftarget",help="autofocus target ID",action="store",dest='aftarget',default=aftarget)

	(options,args)=parser.parse_args()

        logformat= '%(asctime)s %(levelname)s %(message)s'
        logging.basicConfig(filename='/var/log/rts2-debug', level=logging.DEBUG, format= logformat)

        logging.debug('rts2af-queue: starting with options:{0} '.format(options))


	q = Rts2Queue(options.queue,rts2.json.Rts2JSON(url=options.server,username=options.username,password=options.password,verbose=options.verbose))
	focuser= q.getFocuserName()

        # Check if currently a focus run is in progress
        current= str(q.getStateEXEC())
        # [16778242, -1, 0, 0, u'ID of current target']
        pTarget = re.compile( r'(\[[0-9]+,[ ]*)([0-9\-]+)')
        targetID = pTarget.match(current)
        if(targetID):
                if( targetID.group(2)== aftarget):
                        logging.info('rts2af-queue: a focus run is in progress, exiting ')
                        logging.debug('rts2af-queue: end      for options:{0} '.format(options))
                        sys.exit(0)
                else:
                        logging.info('rts2af-queue: current target id: {0} '.format(targetID.group(2)))

        else:
                logging.error('rts2af-queue: could not match string: {0}, received via JSON'.format(current))

	if( focuser=='FOC_FLI'):
		# Check if focuser is in absolute mode
		mode= str(q.getStateFocuser( focuser))
		# [50332679,1,0,0,"temperature compensation absolute, relative to FOC_DEF, no tc"]
		pMode = re.compile( r'(\[[0-9]+,[ ]*)([0-9]+)')
		modeVal = pMode.match(mode)
		if(modeVal):
			if( modeVal.group(2)== '0'): # 0 absolute, 1 relative, 2, no temperature compensation
				logging.info('rts2af-queue: focuser is in absolute temperature compensation mode, exiting ')
				logging.debug('rts2af-queue: end      for options:{0} '.format(options))
				sys.exit(0)
			else:
				logging.info('rts2af-queue: current temperature compensation mode: {0} '.format(modeVal.group(2)))

		else:
			logging.error('rts2af-queue: could not match string: {0}, received via JSON'.format(current))



        logging.info('rts2af-queue: queueing a focus run')


	if options.clear:
		resp = q.clear()
		print "cleared queue {0}".format(options.queue)

	for x in args:
		tars = q.get_target(x)
		if len(tars) == 0:
			print >> sys.stderr, "cannot find target with name {0}".format(x)
			sys.exit(1)
		if options.unique and len(tars) != 1:
		  	print >> sys.stderr, "target name {0} is not unique - returned target with IDs {1}".format(x,'TBD')
			sys.exit(2)

		tids = []	
		for t in tars:
		  	tids.append(t[0])
			print 'Queued to queue {0} target {1} with ID {2} on ra dec {3} {4}'.format(options.queue,t[1],t[0],t[2],t[3])
		resp = q.queue_target(tids)

	print "Queue {0}: {1}".format(options.queue,q)
