#!/bin/bash

DB=`grep "^name.*=" /etc/rts2/rts2.ini | sed -e 's/^.*= *//' | sed -e 's/ *$//' | sed -e 's/"//'`
TARGET=$1

if [ "x$TARGET" == "x" ]; then
  echo "You have to specify target id!"
  exit 1
fi

psql $DB -c "select images.* from images, observations where observations.obs_id = images.obs_id and observations.tar_id=$TARGET order by img_date asc"
