#!/bin/bash

if [ "x$1" = "x-s" ]; then
	if [ "x$4" = "x" ]; then
		exit -1
	fi
	psql stars -c "delete from scripts where tar_id = $1 and camera_name = '$2'"
	psql stars -c "insert into scripts (tar_id, camera_name, script) values ($1, '$2', '$3')"
fi

if [ "x$1" = "x-h" ]; then
	cat <<EOF
Usage:
	$0 -s <target_id> <camera_name> <script>
		Set script to camera
	$0 [target_id [camera_name]]
		Print target specific scripts
EOF
	exit
fi

if [ "x$1" = "x" ]; then
	psql stars -c "select * from scripts"
elif [ "x$2" = "x" ]; then
	psql stars -c "select * from scripts where tar_id = $1"
else
	psql stars -c "select * from scripts where tar_id = $1 and camera_name = '$2'"
fi
