#!/bin/bash

echo "Subject: $1 images for the night ending on " `date`

if [ "x$2" == "x" ]; then
	DAY='1 day'
else
	DAY=$2
fi

echo <<EOF
Images
=======================================================================================
EOF

psql stars -c "select tar_id, img_id, camera_name, images.obs_id, img_date, img_exposure, img_temperature, img_filter, imgrange (astrometry) from images, observations where now() - img_date < '$DAY' and images.obs_id = observations.obs_id order by img_date desc;"

echo <<EOF
=======================================================================================
Observations
=======================================================================================
EOF

psql stars -c "select types.type_description, targets.tar_ra, targets.tar_dec, observations.* from observations, targets, types where types.type_id = targets.type_id and observations.tar_id = targets.tar_id and now () - obs_start < '$DAY' order by obs_start desc;"

echo "Report finished at " `date`
