#!/bin/bash

EPOCH="001"
CAMERAS="B04 B05 B06"
TARGET="`hostname`"
host="bootes@rts2.mayora.csic.es"
id_rsa="$HOME/.ssh/id_rsa"

LOG="$HOME/rts2_find_log_`hostname`"

function find_images {
	target=`printf %05i $1`
	camera=$2
	days=$3

	if [ "x"$days == "x" ]; then
		days=-1
	fi

	if [ "x"$camera == "x" ]; then
		camera=$CAMERAS
	fi

	for cam in $camera; do
		echo Started $target $cam `date` >> $LOG
		eval /usr/local/bin/proxy > /dev/null
		# it has to be made that way; otherwise scp connection may broke
		eval ssh -q -q -i $id_rsa $host "mkdir -p $TARGET/$target/$cam" < /dev/null
		eval scp -B -i $id_rsa -p `find /images/$EPOCH/$cam/$target /trash/images/$EPOCH/$cam/$target -ctime $days -name "*.fits"` $host:$TARGET/$target/$cam < /dev/null
		echo End $target $camera `date` >> $LOG
		echo =============================================================
		echo $target $camera
	done
	return 0
}

if [ "x$1" == "x-" ]; then
	while read x; do
		if echo $x | grep "^[0-9][0-9]" >/dev/null; then
			find_images $x
		fi
	done
else
	find_images $*
fi
