#!/usr/bin/env python

"""
Demonstrator of Python binding to BB.

Copyright (C) 2013 Petr Kubanek <petr@kubanek.net>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
"""

import BaseHTTPServer
from urlparse import parse_qs

PORT=8880

class BBHandler(BaseHTTPServer.BaseHTTPRequestHandler):
	def do_GET(self):
		args = {}
		qi = self.path.find('?')
		if qi >= 0:
			args = parse_qs(self.path[qi+1:])
			self.path = self.path[:qi]
		print "get request", self.path, args

httpd = BaseHTTPServer.HTTPServer(("", PORT), BBHandler)

print "serving at port", PORT
httpd.serve_forever()
