#!/usr/bin/env python

import rts2.json
proxy = rts2.json.createProxy('http://localhost:8880')

ret = proxy.loadJson('/api/create_target', {'tn':'Test','ra':20.34,'dec':23.3})
print ret

print proxy.loadData('/api/schedule', {'id':ret['id']})
print proxy.loadData('/api/confirm', {'id':ret['id'], 'schedule_id':1, 'observatory_id':1})
print proxy.loadData('/api/cancel', {'schedule_id':1})
