#!/usr/bin/env python3

# Focusing script.
# (C) 2018 Petr Kubanek
#

import rts2

import argparse
import gettext
import logging

gettext.install('rts2-shiftautofoc')

parser = argparse.ArgumentParser(
    description=_('Command line processing of shiftstore packages'))

parser.add_argument('files', help=_('files to process'),
    action='append', default=[], type=argparse.FileType('r'))

parser.add_argument('-p', help=_('show progress'),
    action='store_true', dest='progress', default=False)

parser.add_argument('-s', help=_('focusing shifts'),
    action='store', dest='shifts', default='100 50 50 50 50 50 50')
 
parser.add_argument('--horizontal', help=_('shifts are horizontal'),
    action='store_true', dest='horizontal', default=False)

parser.add_argument('-v', help=_('increse verbosity'),
    action='count', dest='verbosity', default=0)

options = parser.parse_args()

logging.basicConfig(level=options.verbosity * 10)

shifts = list(map(int, options.shifts.split()))

sc = rts2.ShiftStore(shifts, options.horizontal, progress=options.progress)

for f in options.files:
    sc.run_on_image(f.name, None, True)

    # partial match
    # sc = ShiftStore([25,75,50,50])
    # for fn in sys.argv[1:]:
    #   sc.runOnImage(fn,3,True)
