#!/usr/bin/python
#   Queue targets to selector
#   (C) 2011 Petr Kubanek, Institute of Physics <kubanek@fzu.cz>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   Please visit http://www.gnu.org/licenses/gpl.html for license informations.

import xmlrpclib
import sys

server = xmlrpclib.ServerProxy('http://user:password@localhost:8889', use_datetime=True)
for x in sys.argv[1:]:
	res=server.rts2.targets.list(x)
	for t in res:
		server.rts2.device.command('SEL','queue plan {0}'.format(t['id']))
		print 'Queued target {0} with ID {1}, on ra dec {2} {3}'.format(t['name'],t['id'],t['ra'],t['dec'])
