#!/usr/bin/python
#   Queue targets to selector
#   (C) 2011 Petr Kubanek, Institute of Physics <kubanek@fzu.cz>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2, or (at your option)
#   any later version.
#
#   Please visit http://www.gnu.org/licenses/gpl.html for license informations.

import json
import urllib
from optparse import OptionParser
import sys
import string

server = 'http://username:password@localhost:8889/api'
resp = json.load(urllib.urlopen(server + '/cmd?' + urllib.urlencode({'d':'SEL','c':'clear plan'})))
print 'cleared queue: {0}'.format(resp['plan_ids'])
