#!/usr/bin/env python

from __future__ import print_function

import argparse
import rts2.rtsapi
import rts2.mpcephem
import numpy
import datetime
import rts2.logger
import sys

parser = argparse.ArgumentParser(description='Calculates pointing data from MPC ephemerid file, and feed this to RTS2 telescope (providing starting RA, DEC and changing skyspeed as long as the program is run)')

parser.add_argument('ephemfile', help='ephemeris files (with skyspeed and PA; default MPC option', action='store', type=argparse.FileType('r'))
parser.add_argument('--server', help='URL to RTS2 XML-RPC server', action='store', dest='server', default='http://localhost:8889')
parser.add_argument('--user', help='RTS2 web server username', action='store', dest='user', default=None)
parser.add_argument('--password', help='password for web user', action='store', dest='password', default=None)
parser.add_argument('--verbose', help='print in/out communication', action='store_true', dest='verbose', default=False)

args = parser.parse_args()

ephs = rts2.mpcephem.MPCEphem(args.ephemfile)

now = numpy.datetime64(datetime.datetime.now())

current = ephs.interpolate(now)

if current[0] == None:
    rts2.logger.log('Cannot calculate RA and DEC from ephemeris file, exiting', rts2.logger.colors.FAIL)
    sys.exit(1)

rts2.logger.log('Calculated RA {0} DEC {1} speeds {2} {3}'.format(current[0], current[1], current[2], current[3]), rts2.logger.colors.OKBLUE)

rts2.logger.log('Exiting')
