#!/usr/bin/env python

# Cube manipulation utilities.
#
# (C) 2017 Petr Kubanek <petr@kubanek.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

from __future__ import print_function

import numpy as np
import sys
from astropy.io import fits
import astropy.time
import os
import rts2.progressbar

import argparse
import datetime
import gettext
gettext.install('rts2-cube')

parser = argparse.ArgumentParser(description=_(
    'Performs various FITS data cube manipulations. Please see option list for details of supported operations.'
))

parser.add_argument(
    '-x',
    help=_('extract cube images into files'),
    action='store', dest='extract', type=str, default=None
)

parser.add_argument(
    'files',
    help=_('files/data cubes to work on'),
    action='append', type=argparse.FileType('r')
)

options = parser.parse_args()

if options.extract:
    for f in options.files:
        ff = fits.open(f)
	tl = len(ff[0].data)
	st = astropy.time.Time(ff[0].header['DATE']).to_datetime()
	print(_('Writing {0} FITS files'.format(tl)))
        for d in range(tl):
            hdu = fits.PrimaryHDU(ff[0].data[d])
	    hdu.header['DATE'] = st
            hdu.writeto(options.extract.format(num = d))
            rts2.progressbar.progress(d, tl)
    print(_('done'))
