#!/bin/bash

DBNAME=$1
PSQL=psql

PSQLDB="$PSQL $DBNAME"

if [ "x$DBNAME" == "x" ]; then
  echo "Usage: $0 <db_name>"
  exit 1
fi

$PSQLDB -c "select * from pg_tables" 2>&1 >/dev/null
if [ $? != 0 ]; then
  echo "Cannot execute psql / you don't have access to database '$DBNAME'"
  exit 2
fi

# build database

$PSQLDB < create/language.sql
$PSQLDB < create/typ_wcs.sql
$PSQLDB < create/functions.sql
$PSQLDB < create/tables.sql
$PSQLDB < create/views.sql

# update to current version

$PSQLDB < update/rel_0_5_1.sql
$PSQLDB < update/rel_0_5_2.sql
$PSQLDB < update/rel_0_6_0.sql
$PSQLDB < update/rel_0_6_1.sql
$PSQLDB < update/rel_0_6_2.sql
$PSQLDB < update/rel_0_7_0.sql

# load init data

$PSQLDB < init_data.sql

# if asked, load Landoldts and planets
echo -n "Would you like to create Landolt calibration fields targets [Y|n]?"
read repl

if [ "x$repl" = 'xY' -o "x$repl" = 'xy' -o "x$repl" = 'x' ]; then
  $PSQLDB < data/landolt.sql
  echo "Landolt fields targets created."
else
  echo "Landolt fields targets skipped."
fi

echo -n "Would you like to create targets for planets [Y|n]?"
read repl
if [ "x$repl" = 'xY' -o "x$repl" = 'xy' -o "x$repl" = 'x' ]; then
  $PSQLDB < data/planets.sql
  echo "Planet targets created"
else
  echo "Planet targets skipped."
fi


# grant rights

$PSQLDB < grant.sql
