#ifndef __RTS2_MESSAGE_T__
#define __RTS2_MESSAGE_T__

typedef enum
{
	MESSAGE_CRITICAL = 0x10,
	MESSAGE_ERROR    = 0x01,
	MESSAGE_WARNING  = 0x02,
	MESSAGE_INFO     = 0x04,
	MESSAGE_DEBUG    = 0x08
} messageType_t;

typedef enum
{
	CRITICAL_TELESCOPE_FAILURE = 0x0110,
	CRITICAL_DOME_FAILURE      = 0x0210,
	CRITICAL_CAMERA_FAILURE    = 0x0310,
	CRITICAL_REQUIRED_FAILURE  = 0x0410
} criticalMessage_t;

#define MESSAGE_MASK_ALL  0xFFFF
#endif							 /* ! __RTS2_MESSAGE_T__ */
