#!/usr/bin/env python

import sys
sys.path.append('../python/rts2')

import kmparse
import unittest

class ParserTest(unittest.TestCase):
	def testParse(self):
		self.assertAlmostEqual(kmparse.kmparse('10k'), 10000)
		self.assertAlmostEqual(kmparse.kmparse('10M'), 10e+6)
		self.assertAlmostEqual(kmparse.kmparse('1234.123M'), 1234.123e+6)
		self.assertAlmostEqual(kmparse.kmparse('1234.123'), 1234.123)
		self.assertAlmostEqual(kmparse.kmparse('1234.123k'), 1234.123e+3)
		self.assertAlmostEqual(kmparse.kmparse('3.123K'), 3.123e+3)

unittest.main()
