#!/usr/bin/env python

import sys
sys.path.append('../python/rts2')

import mpcephem
import unittest
import numpy

class MPCTest(unittest.TestCase):


    def __check_point(self, radec, ra, dec, ra_motion, dec_motion, V):
	self.assertAlmostEqual(radec[0], ra, 4)
	self.assertAlmostEqual(radec[1], dec, 4)
	self.assertAlmostEqual(radec[2], ra_motion, 2)
	self.assertAlmostEqual(radec[3], dec_motion, 2)
	self.assertAlmostEqual(radec[4], V, 1)

    def testLoad(self):
        a = mpcephem.MPCEphem('data/mpecephem_ida')

        date = numpy.datetime64('2017-09-20T10:25:31.4')

        pos = a.interpolate(date)
	self.__check_point(pos, 12.96583, -5.88810, 0.89, -0.38, 15.7)

        date = numpy.datetime64('2017-10-02T10:25:31.4')
        pos = a.interpolate(date)
	self.assertEqual(pos[0], None)
	        

unittest.main()
