#!/usr/bin/env python

import sys
sys.path.append('../python/rts2')

import mpcephem
import unittest
import numpy

class MPCTest(unittest.TestCase):


    def __check_point(self, radec, ra, dec):
	self.assertAlmostEqual(radec[0], ra, 4)
	self.assertAlmostEqual(radec[1], dec, 4)

    def testLoad(self):
        a = mpcephem.MPCEphem('data/mpecephem_ida')

        date = numpy.datetime64('2017-09-20T10:25:31.4')

        pos = a.interpolate(date)
	self.__check_point(pos, 12.96583, -5.88810)
	        

unittest.main()
