#!/bin/bash

echo "Processing $1"

dirname=`dirname $1`
imgname=`echo $1 | sed "s#^$dirname/*##"`

cd $dirname

# image processing

/home/rtopera/bin/bdark $imgname >/dev/null 2>&1
/home/rtopera/bin/detect $imgname #>/dev/null 2>&1
/home/rtopera/bin/past $imgname |grep -v PG
#>/dev/null | grep -v PG
#/home/rtopera/bin/rsol $imgname >/dev/null 2>&1
rm $imgname.sex $imgname.salida

