#!/usr/bin/perl -w

# Script for positionig of the mount to the bightest star.
# $Id$
#
# Used, when astrometry doesn't work.
#
# Petr Kubanek <petr@lascaux.asu.cas.cz>

use strict;

my $file = $ARGV[0];

unless (open (FILE,"<${file}.sex"))
{
  system "/home/rtopera/bin/detect $file";
  open FILE, "<${file}.sex" or die "Cannot open sextrator file!";
}

my @arr;

while (my $in = <FILE>)
{
  next if ($in =~ /^#/);
  my @a = split (/\s+/, $in);
  push @arr, [@a]
}

@arr = sort {$b->[6] <=> $a->[6]} @arr;

#my $ra_err = ($arr[0][2] - 188) * 60 / 376;
#my $dec_err = ($arr[0][3] - 145) * 60 / 290; 

open FILE, "<${file}" or die "Cannot open fits file $file";

my $flip = 0;

while ($a = <FILE>)
{
  # we need there fixed FLIP    =, since FITS uses that format
  if ($a =~ /FLIP    = *(\d)/)
  {
    $flip = $1;
    if ($flip == 0)
    {
      $flip = -1;
    }
    last;
  }
}

#print $flip . "\n";

my $ra_err = + ($arr[0][2] - 160) * 0.2956 * $flip * 2;
my $dec_err = + ($arr[0][3] - 140) * 0.2853 * $flip; 


printf ("%4.4f %4.4f %i", $ra_err, $dec_err, ($arr[0][6]) % 10000);
printf (" (%4.4f,%4.4f)\n", $ra_err, $dec_err);

#foreach my $a (@arr)
#{
#  print $a->[1] . " " . $a->[6] . "\n";
#}
