#!/usr/bin/perl -w

# Script for positionig of the mount to the bightest star.
# $Id$
#
# Used, when astrometry doesn't work.
#
# Petr Kubanek <petr@lascaux.asu.cas.cz>

use strict;

my $file = $ARGV[0];
my $ntries = $ARGV[1];

my $CENTER_RA = 160;
my $CENTER_DEC = 140;

my $COL_RA = 2;
my $COL_DEC = 3;

my $DIAM_RA = 40;
my $DIAM_DEC = 40;

# get the file
unless (open (FILE,"<${file}.sex"))
{
  system "/home/rtopera/bin/detect $file";
  open FILE, "<${file}.sex" or die "Cannot open sextrator file!";
}

my @arr;

while (my $in = <FILE>)
{
  next if ($in =~ /^#/);
  my @a = split (/\s+/, $in);
  # second or so try..
  if ($ntries > 1)
  {
    next if (
        (abs ($a[$COL_RA] - $CENTER_RA) > $DIAM_RA)
     or (abs ($a[$COL_DEC] - $CENTER_DEC) > $DIAM_DEC));
  }
  push @arr, [@a]
}

@arr = sort {$b->[6] <=> $a->[6]} @arr;

open FILE, "<${file}" or die "Cannot open fits file $file";

my $flip = 0;

while ($a = <FILE>)
{
  # we need there fixed FLIP    =, since FITS uses that format
  if ($a =~ /FLIP    = *(\d)/)
  {
    $flip = $1;
    if ($flip == 0)
    {
      $flip = -1;
    }
    last;
  }
}

#print $flip . "\n";

my $ra_err = + ($arr[0][$COL_RA] - $CENTER_RA) * 0.2956 * $flip;
my $dec_err = + ($arr[0][$COL_DEC] - $CENTER_DEC) * 0.2853 * $flip; 


printf ("%4.4f %4.4f %i", $ra_err, $dec_err, ($arr[0][6]) % 10000);
printf (" (%4.4f,%4.4f)\n", $ra_err, $dec_err);

#foreach my $a (@arr)
#{
#  print $a->[1] . " " . $a->[6] . "\n";
#}
