#!/bin/bash

echo "Processing $1"

# try to get it to ds9..
# cat $1|xpaset ds9 fits

# image processing

/home/rtopera/src/bdark $1
/home/rtopera/bin/detect $1
if pwd | grep "CNF1"; then
	/home/rtopera/bin/npast $1 2>$1.past
else
	/home/rtopera/bin/past $1 2>$1.past
fi
