#!/bin/bash
if [ $USER != 'root' ]; then
	echo "Need to be run under root!"
	exit 1
fi

mkdir /darks
mkdir /images
mkdir /flats
mkdir /trash
chgrp -R images /darks /images /flats /trash
chmod g+w /darks /images /flats /trash
